# Generated by Django 2.2.3 on 2019-07-10 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190710_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'TimeLogging',
                'verbose_name_plural': 'TimeLoggings',
            },
        ),
        migrations.AlterModelOptions(
            name='developerinproject',
            options={'verbose_name': 'Developer In Project', 'verbose_name_plural': 'Developer In Projects'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
