# Generated by Django 2.2.3 on 2019-07-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190710_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogging',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelogging',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Task'),
        ),
    ]
