# Generated by Django 2.2.3 on 2019-07-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug_id',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Unique string id'),
        ),
    ]
