# Generated by Django 2.2.3 on 2019-07-15 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190712_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeLogging',
            new_name='TimeJournal',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
