# Generated by Django 2.2.3 on 2019-07-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190716_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
