# Generated by Django 2.2.3 on 2019-07-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190716_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timejournal',
            name='spent_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
