# Generated by Django 2.2.3 on 2019-07-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190717_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timejournal',
            name='id',
        ),
        migrations.AlterField(
            model_name='timejournal',
            name='task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Task'),
            preserve_default=False,
        ),
    ]
