# Generated by Django 2.2.3 on 2019-07-24 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Unique string id')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', tinymce.models.HTMLField(verbose_name='Desrciption')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('developers', models.ManyToManyField(through='core.Developer', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('description', tinymce.models.HTMLField(verbose_name='Desrciption')),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('task_type', models.SmallIntegerField(choices=[(1, 'Feature'), (2, 'Bug')], verbose_name='Task type')),
                ('priority', models.SmallIntegerField(choices=[(1, 'Normal'), (2, 'High'), (3, 'Urgently')], verbose_name='Priority')),
                ('status', models.SmallIntegerField(choices=[(1, 'Free'), (2, 'Performing'), (3, 'Done')], default=1, editable=False, verbose_name='Status')),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL)),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer', to='core.Developer')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TimeJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField()),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
            options={
                'verbose_name': 'TimeJournal',
                'verbose_name_plural': 'TimeJournals',
            },
        ),
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
        migrations.AddField(
            model_name='developer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_of_add', models.DateTimeField(auto_now_add=True, verbose_name='Date of adding')),
                ('for_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
