# Generated by Django 2.2.3 on 2019-07-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190710_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='desciption',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
