# Generated by Django 2.2.3 on 2019-07-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190711_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug_id',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Unique string id'),
        ),
    ]
