# Generated by Django 2.2.3 on 2019-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190715_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timejournal',
            options={'verbose_name': 'TimeJournal', 'verbose_name_plural': 'TimeJournals'},
        ),
        migrations.AlterField(
            model_name='project',
            name='slug_id',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Unique string id'),
        ),
    ]
