# Generated by Django 2.2.3 on 2019-07-17 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190717_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Free'), (2, 'Proccess'), (3, 'Done')], default=1, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
