# Generated by Django 2.2.3 on 2019-07-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190717_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Free'), (2, 'Proccess'), (3, 'Done')], default=1, editable=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='timejournal',
            name='task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Task'),
        ),
    ]
