from django.urls import path, re_path
from .views import (
    HomeView,
    ProjectListView,
    ProjectsCreateView,
    ProjectDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDetailView,
    TaskDeleteView,
    CommentCreateView,
    DevelopersView,
)

urlpatterns = [
    re_path(
        r'^$',
        HomeView.as_view(),
        name="home"),
    path(
        'project/list/',
        ProjectListView.as_view(),
        name='project_list'
    ),
    path(
        'project/add/',
        ProjectsCreateView.as_view(),
        name='create_project'),
    path(
        'project/<slug:slug>/',
        ProjectDetailView.as_view(),
        name='project_detail'),
    path(
        'project/<slug:slug>/task/add/',
        TaskCreateView.as_view(),
        name='create_task'),
    path(
        'project/<slug:slug>/task/<int:pk>/detail/',
        TaskDetailView.as_view(),
        name='detail_task'),
    path(
        'project/<slug:slug>/task/<int:pk>/delete/',
        TaskDeleteView.as_view(),
        name='delete_task'),
    path(
        'project/<slug:slug>/task/<int:pk>/edit/',
        TaskUpdateView.as_view(),
        name='edit_task'),
    path(
        'project/<slug:slug>/task/<int:pk>/comment/add/',
        CommentCreateView.as_view(),
        name='add_comment'),
    path(
        'project/<slug:slug>/add/developer/',
        DevelopersView.as_view(),
        name='add_developer_in_project')
]
