# Generated by Django 2.2.3 on 2019-07-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190710_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Developer')], null=True, verbose_name='Position'),
        ),
    ]
